import { Box, CheckCircle2, Database, RefreshCw, ShieldCheck } from 'lucide-react'
import { getProducts } from '@/lib/catalog'
import { getPublicSupabaseConfig } from '@/lib/public-supabase-config'
import { money } from '@/lib/money'
import { ProductMedia } from '@/components/ProductMedia'

export default async function AdminPreview(){
 const products=await getProducts(); const dbConnected=Boolean(getPublicSupabaseConfig())
 return <main className="admin-page"><aside className="admin-nav"><div className="brand dark"><span className="brand-mark">EO</span><span><b>ECONOM OPTOM</b><small>Управление магазином</small></span></div><nav><b>Обзор</b><span>Заказы</span><span>Каталог</span><span>Синхронизация</span><span>Клиенты</span><span>Настройки</span></nav><small>Client preview</small></aside><section className="admin-main"><header><div><span className="eyebrow">Панель управления</span><h1>Обзор магазина</h1></div><span className="admin-ok"><CheckCircle2 size={16}/>{dbConnected?'База подключена':'Архитектура готова'}</span></header><div className="admin-metrics"><article><Database/><span>Каталог</span><b>{products.length.toLocaleString('ru-RU')}</b><small>активных позиций витрины</small></article><article><RefreshCw/><span>Синхронизация</span><b>{dbConnected?'DB':'Ready'}</b><small>Victoria / Forsage</small></article><article><Box/><span>Заказы</span><b>Ready</b><small>заявки сохраняются отдельно</small></article><article><ShieldCheck/><span>Хранение</span><b>Own DB</b><small>заказы не зависят от источника</small></article></div><div className="admin-grid"><article className="admin-panel"><div className="panel-head"><h2>Каталог</h2><span>{products.length.toLocaleString('ru-RU')} позиций</span></div><div className="admin-products">{products.slice(0,6).map(p=><div key={p.id}><ProductMedia src={p.imageUrl} alt={p.name}/><span><b>{p.name}</b><small>{p.sku} • {p.packSize} шт.</small></span><strong>{money(p.unitPrice,p.currency??'UAH')}</strong><i>Активен</i></div>)}</div></article><article className="admin-panel sync-panel"><div className="panel-head"><h2>Синхронизация</h2><span className="green-dot">snapshot загружен</span></div><div className="sync-flow"><p><b>01</b><span>Получить товары<small>Victoria / Forsage</small></span></p><p><b>02</b><span>Нормализовать<small>SKU, цена, упаковка, размеры, фото</small></span></p><p><b>03</b><span>Обновить базу<small>1922 релевантные позиции загружены</small></span></p><p><b>04</b><span>Подключить live sync<small>после официального API/export доступа</small></span></p></div><small className="panel-note">Сейчас витрина показывает импортированный snapshot актуального публичного каталога. Постоянную автоматическую синхронизацию включаем после получения официального доступа клиента.</small></article></div></section></main>
}
