import Link from 'next/link'
import { ArrowRight, Box, Check, RefreshCw, ShieldCheck, Truck } from 'lucide-react'
import { getProducts } from '@/lib/catalog'
import { ProductCard } from '@/components/ProductCard'

export default async function Home(){
 const products=await getProducts()
 const heroMain=products.find(p=>p.sourceId==='1120136')??products.find(p=>p.category==='Обувь')??products[0]
 const heroSide=products.find(p=>p.sourceId==='1117620')??products.find(p=>p.category==='Аксессуары')??products[1]??heroMain
 const featured=[...products.filter(p=>p.category==='Обувь').slice(0,4),...products.filter(p=>p.category==='Одежда').slice(0,2),...products.filter(p=>p.category==='Аксессуары').slice(0,2)]
 return <main>
   <section className="hero shell">
    <div className="hero-copy"><span className="eyebrow">Оптовая платформа для магазинов</span><h1>Одежда и обувь<br/><em>готовыми упаковками.</em></h1><p>Быстрый каталог для предпринимателей: реальные фото, размеры, количество в упаковке и её стоимость видны сразу.</p><div className="hero-actions"><Link className="primary" href="/catalog">Смотреть каталог <ArrowRight size={17}/></Link><a className="secondary" href="#how">Как заказать</a></div><div className="proof-row"><div><b>{products.length.toLocaleString('ru-RU')}</b><span>позиций в актуальном snapshot</span></div><div><b>3</b><span>группы ассортимента</span></div><div><b>24/7</b><span>приём заявок</span></div></div></div>
    <div className="hero-gallery"><div className="hero-main"><img src={heroMain.imageUrl} alt={heroMain.name}/><span><small>Victoria</small><b>{heroMain.name}</b></span></div><div className="hero-side"><img src={heroSide.imageUrl} alt={heroSide.name}/></div><div className="hero-card"><RefreshCw size={18}/><span><b>Каталог обновляется централизованно</b><small>ассортимент • цены • размеры • фото</small></span></div></div>
   </section>
   <section className="trust shell"><span><ShieldCheck/>Проверка заказа менеджером</span><span><Box/>Продажа упаковками</span><span><Truck/>Доставка по Украине</span><span><RefreshCw/>Готово к автоматической синхронизации</span></section>
   <section className="section shell"><div className="section-head"><div><span className="eyebrow">Ассортимент</span><h2>Выберите товар</h2></div><Link href="/catalog">Весь каталог <ArrowRight size={16}/></Link></div><div className="product-grid">{featured.map(p=><ProductCard product={p} key={p.id}/>)}</div></section>
   <section id="wholesale" className="wholesale"><div className="shell wholesale-inner"><div><span className="eyebrow light">Для оптового покупателя</span><h2>Сразу понятно,<br/>сколько стоит упаковка.</h2><p>Без пересчётов в мессенджере. Цена за единицу, размерный ряд, количество и итог видны до заказа.</p></div><div className="wholesale-cards"><article><b>01</b><h3>Цена</h3><p>Цена за единицу и автоматический расчёт стоимости всей упаковки.</p></article><article><b>02</b><h3>Размеры</h3><p>Размерный ряд и количество единиц показываются прямо в карточке.</p></article><article><b>03</b><h3>Подтверждение</h3><p>Менеджер проверяет фактическое наличие перед предоплатой.</p></article></div></div></section>
   <section id="how" className="section shell"><div className="section-head"><div><span className="eyebrow">Простой процесс</span><h2>Заказ за четыре шага</h2></div></div><div className="steps"><article><b>01</b><h3>Выберите товар</h3><p>Один каталог, поиск, группы, размеры, сезон и артикул.</p></article><article><b>02</b><h3>Добавьте упаковки</h3><p>Количество упаковок меняется прямо в корзине.</p></article><article><b>03</b><h3>Отправьте заявку</h3><p>Заказ сохраняется вместе с составом и контактами.</p></article><article><b>04</b><h3>Получите подтверждение</h3><p>Наличие, предоплата и доставка согласовываются до отправки.</p></article></div></section>
   <section className="sync-section shell"><div><span className="eyebrow">Каталог без ручной рутины</span><h2>Ассортимент обновляется.<br/>Заказы остаются на месте.</h2><p>Магазин хранит собственную актуальную копию ассортимента. Новые позиции, цены, размеры и фото можно обновлять централизованно, а история заказов остаётся независимой от поставщика.</p><ul><li><Check/>Новые позиции добавляются в каталог</li><li><Check/>Цены, размеры и упаковки обновляются</li><li><Check/>Пропавшие позиции архивируются безопасно</li><li><Check/>Заказы хранятся отдельно от поставщика</li></ul></div><div className="sync-console"><div><span>CATALOG SNAPSHOT</span><b>READY</b></div><p><span>Источник</span><b>Victoria / Forsage</b></p><p><span>Snapshot</span><b>{products.length.toLocaleString('ru-RU')} товаров</b></p><p><span>Витрина</span><b>Собственная БД</b></p><p><span>Заказы</span><b>Независимое хранение</b></p><small>Постоянная автоматическая синхронизация включается после подключения официального доступа клиента к каталогу.</small></div></section>
   <footer><div className="shell footer-inner"><div className="brand"><span className="brand-mark">EO</span><span><b>ECONOM OPTOM</b><small>одежда • обувь • опт</small></span></div><p>Одесса • Оптовые поставки по Украине</p></div></footer>
 </main>
}
