import Link from 'next/link'
import { ArrowRight, Box, Check, RefreshCw, ShieldCheck, Truck } from 'lucide-react'
import { getProducts } from '@/lib/catalog'
import { ProductCard } from '@/components/ProductCard'

export default async function Home(){
 const products=await getProducts(); const featured=products.slice(0,8)
 return <main>
   <section className="hero shell">
    <div className="hero-copy"><span className="eyebrow">Оптовая платформа для магазинов</span><h1>Одежда и обувь<br/><em>готовыми ящиками.</em></h1><p>Быстрый каталог для предпринимателей: размеры, количество в упаковке и стоимость всего ящика видны сразу.</p><div className="hero-actions"><Link className="primary" href="/catalog">Смотреть каталог <ArrowRight size={17}/></Link><a className="secondary" href="#how">Как заказать</a></div><div className="proof-row"><div><b>{products.length}</b><span>товаров с реальными фото</span></div><div><b>8–24</b><span>пар в упаковке</span></div><div><b>24/7</b><span>приём заявок</span></div></div></div>
    <div className="hero-gallery"><div className="hero-main"><img src={products[3].imageUrl} alt={products[3].name}/><span><small>Victoria</small><b>{products[3].name}</b></span></div><div className="hero-side"><img src={products[0].imageUrl} alt={products[0].name}/></div><div className="hero-card"><RefreshCw size={18}/><span><b>Каталог обновляется централизованно</b><small>ассортимент • цены • размеры • фото</small></span></div></div>
   </section>
   <section className="trust shell"><span><ShieldCheck/>Проверка заказа менеджером</span><span><Box/>Продажа ящиками</span><span><Truck/>Доставка по Украине</span><span><RefreshCw/>Автообновление каталога</span></section>
   <section className="section shell"><div className="section-head"><div><span className="eyebrow">Новые поступления</span><h2>Выберите модель</h2></div><Link href="/catalog">Весь каталог <ArrowRight size={16}/></Link></div><div className="product-grid">{featured.map(p=><ProductCard product={p} key={p.id}/>)}</div></section>
   <section id="wholesale" className="wholesale"><div className="shell wholesale-inner"><div><span className="eyebrow light">Для оптового покупателя</span><h2>Сразу понятно,<br/>сколько стоит ящик.</h2><p>Без пересчётов в мессенджере. Цена пары, размерный ряд, упаковка и итог видны до заказа.</p></div><div className="wholesale-cards"><article><b>01</b><h3>Цена</h3><p>Цена за пару и автоматический расчёт стоимости упаковки.</p></article><article><b>02</b><h3>Размеры</h3><p>Размерный ряд и количество единиц в ящике в каждой карточке.</p></article><article><b>03</b><h3>Подтверждение</h3><p>Менеджер проверяет фактическое наличие перед предоплатой.</p></article></div></div></section>
   <section id="how" className="section shell"><div className="section-head"><div><span className="eyebrow">Простой процесс</span><h2>Заказ за четыре шага</h2></div></div><div className="steps"><article><b>01</b><h3>Выберите товар</h3><p>Категории, поиск, размеры, сезон и артикул.</p></article><article><b>02</b><h3>Добавьте ящики</h3><p>Количество упаковок меняется прямо в корзине.</p></article><article><b>03</b><h3>Отправьте заявку</h3><p>Заказ сохраняется вместе с составом и контактами.</p></article><article><b>04</b><h3>Получите подтверждение</h3><p>Наличие, предоплата и доставка согласовываются до отправки.</p></article></div></section>
   <section className="sync-section shell"><div><span className="eyebrow">Каталог без ручной рутины</span><h2>Ассортимент обновляется.<br/>Заказы остаются на месте.</h2><p>Магазин хранит собственную актуальную копию ассортимента. Новые позиции, цены, размеры и фото можно обновлять централизованно, а история заказов остаётся независимой от поставщика.</p><ul><li><Check/>Новые позиции добавляются в каталог</li><li><Check/>Цены, размеры и упаковки обновляются</li><li><Check/>Пропавшие позиции архивируются безопасно</li><li><Check/>Заказы хранятся отдельно от поставщика</li></ul></div><div className="sync-console"><div><span>CATALOG SYNC</span><b>READY</b></div><p><span>Источник</span><b>Victoria / Forsage</b></p><p><span>Snapshot</span><b>{products.length} товаров</b></p><p><span>Витрина</span><b>Собственная БД</b></p><p><span>Заказы</span><b>Независимое хранение</b></p><small>Полная автоматическая синхронизация включается после подключения официального доступа к каталогу.</small></div></section>
   <footer><div className="shell footer-inner"><div className="brand"><span className="brand-mark">EO</span><span><b>ECONOM OPTOM</b><small>одежда • обувь • опт</small></span></div><p>Одесса • Оптовые поставки по Украине</p></div></footer>
 </main>
}
