create extension if not exists pgcrypto;

create table if not exists public.econom_products (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'victoria_forsage',
  source_id text not null unique,
  sku text not null,
  slug text not null unique,
  name text not null,
  category text,
  brand text,
  gender text,
  season text,
  material text,
  unit_price_uah numeric(12,2) not null check (unit_price_uah >= 0),
  pack_size integer not null check (pack_size > 0),
  size_grid text,
  image_urls jsonb not null default '[]'::jsonb,
  attributes jsonb not null default '{}'::jsonb,
  source_url text,
  is_active boolean not null default true,
  source_updated_at timestamptz,
  last_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.econom_order_requests (
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity,
  company_name text not null,
  contact_name text not null,
  phone text not null,
  city text not null,
  delivery_method text,
  comment text,
  total_uah numeric(12,2) not null default 0,
  status text not null default 'new' check (status in ('new','confirmed','awaiting_payment','paid','assembling','shipped','completed','cancelled')),
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.econom_sync_runs (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'victoria_forsage',
  status text not null check (status in ('running','success','partial','failed')),
  received integer not null default 0,
  created_count integer not null default 0,
  updated_count integer not null default 0,
  archived_count integer not null default 0,
  error_count integer not null default 0,
  errors jsonb not null default '[]'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.econom_supplier_events (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'victoria_forsage',
  product_ids jsonb not null default '[]'::jsonb,
  change_types jsonb not null default '[]'::jsonb,
  status text not null default 'pending' check (status in ('pending','processing','processed','failed')),
  attempts integer not null default 0,
  last_error text,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

alter table public.econom_products enable row level security;
alter table public.econom_order_requests enable row level security;
alter table public.econom_sync_runs enable row level security;
alter table public.econom_supplier_events enable row level security;

drop policy if exists "econom public read active products" on public.econom_products;
create policy "econom public read active products" on public.econom_products for select using (is_active = true);

create index if not exists econom_products_active_category_idx on public.econom_products(is_active, category);
create index if not exists econom_products_sku_idx on public.econom_products(sku);
create index if not exists econom_order_requests_created_idx on public.econom_order_requests(created_at desc);
create index if not exists econom_order_requests_status_idx on public.econom_order_requests(status);
create index if not exists econom_supplier_events_status_received_idx on public.econom_supplier_events(status, received_at);

insert into public.econom_products (source_id,sku,slug,name,category,gender,season,material,unit_price_uah,pack_size,size_grid,image_urls,source_url,is_active)
values
('1117620','Ф11-2 mix','sapogi-f11-2-mix','Сапоги Ф11-2 mix','Сапоги','Детское','Зима','Искусственная кожа / замша',185,16,'34–38','["https://paradobuvi.ua/import_files/storage/0/import_files/de/de93a5fd-9c6d-11f0-baf2-005056003f72.jpg?v=1759096802"]','https://www.forsage-studio.com/victoria',true),
('1117617','Ф11-6 mix','sapogi-f11-6-mix','Сапоги Ф11-6 mix','Сапоги','Детское','Зима','Искусственная кожа',185,16,'34–38','["https://paradobuvi.ua/import_files/storage/0/import_files/de/de93a5fc-9c6d-11f0-baf2-005056003f72.jpg?v=1759096801"]','https://www.forsage-studio.com/victoria',true),
('1117616','Ф11-5 mix','sapogi-f11-5-mix','Сапоги Ф11-5 mix','Сапоги','Детское','Зима','Искусственная кожа',185,16,'34–38','["https://paradobuvi.ua/import_files/storage/0/import_files/de/de93a5fb-9c6d-11f0-baf2-005056003f72.jpg?v=1759096801"]','https://www.forsage-studio.com/victoria',true),
('1120136','N88-09 mix','uggi-n88-09-mix','Угги N88-09 mix','Угги','Детское','Зима','Текстиль',255,10,'31–35','["https://paradobuvi.ua/import_files/storage/0/import_files/49/49f90be5-a448-11f0-baf2-005056003f72.jpg?v=1759960763"]','https://www.forsage-studio.com/victoria/1120136-uggi-n88-09-mix',true),
('victoria-31-21','31-21 mix','uggi-31-21-mix','Угги 31-21 mix','Угги','Детское','Зима','Текстиль',255,10,'31–35','["https://paradobuvi.ua/import_files/storage/0/import_files/49/49f90be6-a448-11f0-baf2-005056003f72.jpg?v=1759960764"]','https://www.forsage-studio.com/victoria',true),
('victoria-61-16','61-16 mix','krossovki-61-16-mix','Кроссовки 61-16 mix','Кроссовки','Детское','Деми','Искусственная кожа',173,20,'27–31','["https://paradobuvi.ua/import_files/storage/0/import_files/f4/f4f665fb-a8d5-11f0-baf2-005056003f72.jpg?v=1760476082"]','https://www.forsage-studio.com/victoria',true),
('victoria-86-68','86-68 утеплені mix','krossovki-86-68-mix','Кроссовки 86-68 утепленные mix','Кроссовки','Детское','Деми','Искусственная кожа / плащевка',173,20,'27–31','["https://paradobuvi.ua/import_files/storage/0/import_files/f4/f4f665fa-a8d5-11f0-baf2-005056003f72.jpg?v=1760476082"]','https://www.forsage-studio.com/victoria',true),
('victoria-64-46','64-46 утеплені mix','krossovki-64-46-mix','Кроссовки 64-46 утепленные mix','Кроссовки','Детское','Деми','Искусственный материал',173,20,'27–31','["https://paradobuvi.ua/import_files/storage/0/import_files/f4/f4f665f9-a8d5-11f0-baf2-005056003f72.jpg?v=1760476082"]','https://www.forsage-studio.com/victoria',true),
('victoria-72-11','72-11 mix','krossovki-72-11-mix','Кроссовки 72-11 mix','Кроссовки','Детское','Деми','Искусственная замша / текстиль',210,12,'32–37','["https://paradobuvi.ua/import_files/storage/0/import_files/49/49f90be4-a448-11f0-baf2-005056003f72.jpg?v=1759960763"]','https://www.forsage-studio.com/victoria',true),
('victoria-va03','VA03 pink','tapki-va03-pink','Тапочки VA03 pink','Тапочки','Детское','Деми','Искусственный материал',57,10,'14–18','["https://paradobuvi.ua/import_files/storage/0/import_files/c6/c6ea47cb-3596-11ef-bad8-00505600d7fd.jpg"]','https://www.forsage-studio.com/victoria',true),
('victoria-2-22','2-22','krossovki-2-22','Кроссовки 2-22','Кроссовки','Детское','Деми','Искусственная кожа / текстиль',203,8,'31–35','["https://paradobuvi.ua/import_files/storage/0/import_files/8b/8b239746-7d83-11f0-baf2-005056003f72.jpg?v=1755732438"]','https://www.forsage-studio.com/victoria',true),
('1117366','33-5 mix','sapogi-33-5-mix','Сапоги 33-5 mix','Сапоги','Детское','Зима','Искусственный материал',185,16,'34–38','["https://paradobuvi.ua/import_files/storage/0/import_files/d8/d8b3e377-9c50-11f0-baf2-005056003f72.jpg?v=1771966877"]','https://www.forsage-studio.com/victoria',true),
('1117364','33-7 mix','sapogi-33-7-mix','Сапоги 33-7 mix','Сапоги','Детское','Зима','Искусственный материал',185,16,'34–38','["https://paradobuvi.ua/import_files/storage/0/import_files/d8/d8b3e376-9c50-11f0-baf2-005056003f72.jpg?v=1771966877"]','https://www.forsage-studio.com/victoria',true)
on conflict (source_id) do update set
 sku=excluded.sku, slug=excluded.slug, name=excluded.name, category=excluded.category, gender=excluded.gender,
 season=excluded.season, material=excluded.material, unit_price_uah=excluded.unit_price_uah,
 pack_size=excluded.pack_size, size_grid=excluded.size_grid, image_urls=excluded.image_urls,
 source_url=excluded.source_url, is_active=excluded.is_active, last_synced_at=now(), updated_at=now();

create or replace function public.econom_submit_order_request(
  p_company_name text,
  p_contact_name text,
  p_phone text,
  p_city text,
  p_delivery_method text,
  p_comment text,
  p_items jsonb
)
returns table(number bigint, total_uah numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_requested_count integer;
  v_valid_count integer;
  v_items jsonb;
  v_total numeric(12,2);
  v_number bigint;
begin
  if length(trim(coalesce(p_company_name,''))) = 0
    or length(trim(coalesce(p_contact_name,''))) = 0
    or length(regexp_replace(coalesce(p_phone,''), '[^0-9]', '', 'g')) < 8
    or length(trim(coalesce(p_city,''))) = 0
    or length(trim(coalesce(p_delivery_method,''))) = 0 then
    raise exception 'invalid_contact_data';
  end if;
  if jsonb_typeof(p_items) <> 'array' then raise exception 'invalid_items'; end if;
  v_requested_count := jsonb_array_length(p_items);
  if v_requested_count < 1 or v_requested_count > 100 then raise exception 'invalid_items'; end if;
  if exists (
    select 1 from jsonb_array_elements(p_items) line
    where coalesce(line->>'source_id','') = ''
       or coalesce(line->>'boxes','') !~ '^[1-9][0-9]{0,2}$'
       or (line->>'boxes')::integer > 100
  ) then raise exception 'invalid_items'; end if;

  with requested as (
    select line->>'source_id' as source_id, (line->>'boxes')::integer as boxes
    from jsonb_array_elements(p_items) line
  ), resolved as (
    select p.source_id, p.sku, p.name, r.boxes, p.pack_size,
           p.unit_price_uah as unit_price,
           (p.unit_price_uah * p.pack_size * r.boxes)::numeric(12,2) as line_total
    from requested r join public.econom_products p on p.source_id = r.source_id and p.is_active = true
  )
  select count(*),
         coalesce(jsonb_agg(jsonb_build_object('source_id',source_id,'sku',sku,'name',name,'boxes',boxes,'pack_size',pack_size,'unit_price',unit_price,'line_total',line_total) order by source_id),'[]'::jsonb),
         coalesce(sum(line_total),0)::numeric(12,2)
    into v_valid_count, v_items, v_total
  from resolved;

  if v_valid_count <> v_requested_count then raise exception 'catalog_changed'; end if;
  insert into public.econom_order_requests(company_name,contact_name,phone,city,delivery_method,comment,total_uah,status,items)
  values(left(trim(p_company_name),120),left(trim(p_contact_name),100),left(trim(p_phone),40),left(trim(p_city),100),left(trim(p_delivery_method),80),nullif(left(trim(coalesce(p_comment,'')),1000),''),v_total,'new',v_items)
  returning econom_order_requests.number into v_number;
  return query select v_number,v_total;
end;
$$;

revoke all on function public.econom_submit_order_request(text,text,text,text,text,text,jsonb) from public;
grant execute on function public.econom_submit_order_request(text,text,text,text,text,text,jsonb) to anon, authenticated;
