create extension if not exists pgcrypto;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'victoria_forsage',
  source_id text not null unique,
  sku text not null,
  slug text not null unique,
  name text not null,
  category text,
  brand text,
  gender text,
  season text,
  material text,
  unit_price_uah numeric(12,2) not null check (unit_price_uah >= 0),
  pack_size integer not null check (pack_size > 0),
  size_grid text,
  image_urls jsonb not null default '[]'::jsonb,
  attributes jsonb not null default '{}'::jsonb,
  source_url text,
  is_active boolean not null default true,
  source_updated_at timestamptz,
  last_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_requests (
  id uuid primary key default gen_random_uuid(),
  number bigint generated by default as identity,
  company_name text not null,
  contact_name text not null,
  phone text not null,
  city text not null,
  delivery_method text,
  comment text,
  total_uah numeric(12,2) not null default 0,
  status text not null default 'new' check (status in ('new','confirmed','awaiting_payment','paid','assembling','shipped','completed','cancelled')),
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sync_runs (
  id uuid primary key default gen_random_uuid(),
  source text not null default 'victoria_forsage',
  status text not null check (status in ('running','success','partial','failed')),
  received integer not null default 0,
  created_count integer not null default 0,
  updated_count integer not null default 0,
  archived_count integer not null default 0,
  error_count integer not null default 0,
  errors jsonb not null default '[]'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

alter table public.products enable row level security;
alter table public.order_requests enable row level security;
alter table public.sync_runs enable row level security;

-- Public storefront can read active products only.
create policy "public read active products" on public.products for select using (is_active = true);

-- No public order policies. Wholesale requests are validated and inserted server-side with the service role.

create index if not exists products_active_category_idx on public.products(is_active, category);
create index if not exists products_sku_idx on public.products(sku);
create index if not exists order_requests_created_idx on public.order_requests(created_at desc);
create index if not exists order_requests_status_idx on public.order_requests(status);
